	<script src="//code.jquery.com/jquery-3.2.1.min.js"></script>

<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->

	<script src="js/main.js"></script>
	
	<script src="fancybox/jquery.fancybox.js"></script>
	
</body>
</html>