
		<div class="container-contact2-form-btn">
						<div class="wrap-contact2-form-btn">
							<div class="contact2-form-bgbtn"></div>
							<button name="album" class="contact2-form-btn">
								<a href="?page=approve">Approve Images</a>
							</button>
						</div>
		</div>
		
		<form method="post" action="<?php echo (htmlspecialchars($_SERVER["PHP_SELF"]) . '?page=moderator&&edit=true');?>" >
