
		<div class="container-contact2-form-btn">
						<div class="wrap-contact2-form-btn">
							<div class="contact2-form-bgbtn"></div>
							<button name="album" class="contact2-form-btn">
								<a href="?page=approve">Approve Images</a>
							</button>
						</div>
					</div>

<button type="button" id="sortbyfirstname" class="btn btn-default btn-md edit btn-outline-primary">
          <span class="oi oi-check" title="check" aria-hidden="true"></span>Sort Alphabetically by First Name
</button>
<button type="butto" id="sortbylastname"  class="btn btn-default btn-md edit btn-outline-primary">
          <span class="oi oi-check" title="check" aria-hidden="true"></span>Sort Alphabetically by Last Name
</button>
<button type="butto" id="sortbyuploaddate" name="save" value="save" class="btn btn-default btn-md edit btn-outline-primary">
          <span class="oi oi-check" title="check" aria-hidden="true"></span>Sort by upload date
</button>