<div class="container">
	<div class="row align-items-center justify-content-center">
<button type="button" class="btn btn-default btn-md edit btn-outline-primary">
          <span class="oi oi-check" title="check" aria-hidden="true"></span>Approve
        </button>
<div class="col-1"></div>
<button type="button" class="btn btn-default btn-md edit btn-outline-danger">
          <span class="oi oi-x" title="x" aria-hidden="true"></span> Remove 
</button>
</div>
</div>