
		<div class="container-contact2-form-btn">
						<div class="wrap-contact2-form-btn">
							<div class="contact2-form-bgbtn"></div>
							<button name="album" class="contact2-form-btn">
								<a href="?page=edit">Approve Images</a>
							</button>
						</div>
					</div>

<div class="container">
<div class="row masonry-grid">
  <div class="col masonry-column" id="column1">

  </div>
  <div class="col masonry-column" id="column2">

  </div>
  <div class="col masonry-column" id="column3">

  </div>
  <div class="col masonry-column" id="column4">

  </div>
</div>
</div>